---
- name: Converge
  hosts: all
  vars:
    ferm_role_debug: true
    duo_unix_duo_ikey: integration-key
    duo_unix_duo_skey: secret-key
    duo_unix_duo_host: api-xxxxxx.duosecurity.com
    dup_unix_groups: integration
  roles:
    - role: escapace.duo_unix
